# Exported from Render on 2025-04-28T16:25:17Z
services:
  - type: web
    name: durin-website
    runtime: node
    repo: https://github.com/namestonehq/durin-website
    branch: prod
    plan: starter
    envVars:
      - key: NEXT_PUBLIC_FACTORY_ADDRESS
        sync: false
      - key: NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_ALCHEMY_API_KEY
        sync: false
      - key: SEPOLIA_SUBGRAPH_URL
        sync: false
      - key: SUBGRAPH_URL
        sync: false
      - key: PORT
        sync: false
    region: ohio
    buildCommand: npm install; npm run build
    startCommand: npm run start
    domains:
      - www.durin.dev
      - durin.dev
    autoDeploy: true
  - type: web
    name: durin-website-staging
    runtime: node
    repo: https://github.com/namestonehq/durin-website
    plan: free
    envVars:
      - key: PORT
        sync: false
      - fromGroup: Durin-website
    region: ohio
    buildCommand: npm install; npm run build
    startCommand: npm run start
version: "1"
